[project]
name = "software"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faster-whisper>=1.2.1",
    "pyaudio>=0.2.14",
    "webrtcvad>=2.0.10",
]
